# Generated by Django 3.1.2 on 2020-11-08 00:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TaskList",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("slug", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "Task List",
                "verbose_name_plural": "Task Lists",
            },
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("is_done", models.BooleanField(default=False)),
                (
                    "task_list",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="tasks", to="tasks.tasklist"
                    ),
                ),
            ],
            options={
                "verbose_name": "Task Item",
                "verbose_name_plural": "Task Items",
            },
        ),
    ]
